### ISSUE TITLE
STAGING- Click through image

### ISSUE THREAD

**Issue by WotCLexie** [Gamesight/MTGA-forums#13]
Could we remove the "Dev Tracker" from the left-hand side of our forums, and instead replace it with a graphic that we can click through to another web page? 

We no longer track bugs on the forums and use a different page, so this is confusing to our users. 
![Capture](https://user-images.githubusercontent.com/46498619/63131656-56357900-bf73-11e9-9f77-5107fafe9103.PNG)

**Comment by doman412** [comment]
Hey @WotCLexie, the Dev Tracker is similar to recent posts but only shows posts/replies for official wotc members. It is not related to any bug tracking on the forums. It's a place for members to keep up with what the 'devs' are saying. The name could be changed to better reflect this, something like `Official Replies`, or we could remove it if you'd like.

**Comment by WotCLexie** [comment]
Oh, gotcha! That can stay, then. Changing the name to “Official Replies” would be great, then.

Is there a way to archive and permanently hide all of our closed-beta posts, but not have them visible to the public any longer? Also, can we remove the post count for users? All on staging, not on our current forums.
