### ISSUE TITLE
Revert timestamps on forum posts

### ISSUE THREAD

**Issue by adamlieb** [Gamesight/MTGA-forums#2]
**Is your feature request related to a problem? Please describe.**
The current time stamps are confusing. Specifically "3m" which apparently means "3 months"

**Describe the solution you'd like**
Revert timestamps to how the platform normally works.

**Describe alternatives you've considered**
There are no alternatives considered.

**Additional context**
This post is 2 months old, but many (including myself) thought it was "2 minutes" old. 
![image](https://user-images.githubusercontent.com/4257810/49755742-f7925f80-fc6d-11e8-97ca-c29a168a6e9a.png)

**Comment by doman412** [comment]
I've reverted the timestamp label to its original format of `X {time} ago`
`2m` -> `2 months ago`
`2min` -> `2 minutes ago`
